name: Zoom Clone Deployment Workflow

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build zoom-clone
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zoom-clone

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: zoom-clone/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build zoom clone app
        run: npm run build

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/zoom-clone .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/zoom-clone
