name: Zoom Clone Deployment Workflow

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build zoom-clone
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zoom-clone


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build zoom clone app
        run: npm run build

      - name: Build and Publish Docker Image
        run: |
          echo "Running Docker build and push commands..."
          echo "Repository name: zoom-clone:latest"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/zoom-clone .
          echo "Attempting to log in to Docker Hub..."
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          echo "Docker login succeeded. Pushing image..."
          docker push ${{ secrets.DOCKER_USERNAME }}/zoom-clone
        working-directory: ./zoom-clone