name: Zoom Clone Deployment Workflow

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build zoom-clone
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zoom-clone
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd
         
      - name: List files in the repository
        run: ls -la

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build zoom clone app
        run: npm run build

      - name: Build and Publish Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/zoom-clone:latest ./zoom-clone
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/zoom-clone:latest
      



